import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout/page";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
        <Toaster />
      </body>
    </html>
  );
}
