import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import './globals.css';
import ToastProvider from '@src/components/providers/Toast/Toast';
import MainLayout from '@src/components/layout/MainLayout';
import Providers from '@src/app/providers';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <ToastProvider />

          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
