import type { Metadata } from 'next';
import './globals.css';
import Layout from '@src/components/Layout';
import ToastProvider from '@src/components/Providers/ToastProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <ToastProvider />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
