import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@src/components/ui/sonner';
import React from 'react';
import LayoutWrapper from '@src/components/LayoutWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutWrapper>{children}</LayoutWrapper>
        <Toaster />
      </body>
    </html>
  );
}
